version: '3.9'

services:
  server:
    image: shareit
    container_name: shareit-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
  db:
    image: postgres:17-alpine
    container_name: shareit-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=shareit